<Project>

    <Import Project="../Directory.Build.props" Condition="Exists('../Directory.Build.props')" />

    <PropertyGroup>
        <SimpleExecVersion>12.0.0</SimpleExecVersion>
        <NuGetVersion>6.9.1</NuGetVersion>
        <OctokitVersion>13.0.0</OctokitVersion>
    </PropertyGroup>

</Project>